//
// Created by on 2020/10/13.
//

#include <auxiliary.hpp>
#if MAJOR_NUM == 1 || MAJOR_NUM == 3
#include <Gauss_elimination.hpp>
#endif
#if MAJOR_NUM == 2 || MAJOR_NUM == 3
#include <Cholesky_decompose.hpp>
#endif
#if MINOR_NUM == 2
#include <random>
#define auxiliary(a, b, c) auxiliary_impl<T, true>(a, #a, b, c)
#else
#define auxiliary(a, b, c) auxiliary_impl(a, #a, b, c)
#endif

using namespace happy_matrix;

int main(){
#if MINOR_NUM == 1
    using T = long double;
    matrix<T> to_decompose(84, vector<T>(84));
    vector<T> to_solve(84);

    for (size_t i = 0; i < 84; i++){
        if (i != 0)
            to_decompose[i][i - 1] = 8;
        to_decompose[i][i] = 6;
        if (i != 83)
            to_decompose[i][i + 1] = 1;
    }

    to_solve[0] = 7;
    to_solve[83] = 14;
    for (int i = 1; i < 83; ++i)
        to_solve[i] = 15;
#elif MINOR_NUM == 2
    using T = double;
    matrix<T> to_decompose(100, vector<T>(100));
    vector<T> to_solve(100);
    std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_real_distribution<> dis(-1.0, 1.0);

    for (size_t i = 0; i < 100; ++i){
        if (i != 0)
            to_decompose[i][i - 1] = 1;
        to_decompose[i][i] = 10;
        if (i != 83)
            to_decompose[i][i + 1] = 1;
    }

    for (size_t i = 0; i < 100; ++i) {
        // Use dis to transform the random unsigned int generated by gen into a
        // T in [-1, 1). Each call to dis(gen) generates a new random T
        to_solve[i] = dis(gen);
    }
#else
    using T = long double;
    matrix<T> to_decompose(40, vector<long double>(40));
    vector<T> to_solve(40);


    for (size_t i = 0; i < 40; ++i)
        for (size_t j = 0; j < 40; ++j){
            to_decompose[i][j] += 1.0/(i + j + 1); //NOLINT
            to_solve[i] += 1.0/(i + j + 1); //NOLINT
        }
#endif

#if MAJOR_NUM == 1 || MAJOR_NUM == 3
    auxiliary(Gauss_solve_normal, to_decompose, to_solve);
    auxiliary(Gauss_solve_column, to_decompose, to_solve);
#endif
#if MAJOR_NUM == 2 || MAJOR_NUM == 3
    auxiliary(LLT_solve, to_decompose, to_solve);
    auxiliary(LDLT_solve, to_decompose, to_solve);
#endif
}